### ISSUE TITLE
Convert proto buf to JS object?

### ISSUE THREAD

**Issue by niftylettuce** [wajatimur/node-phonenumber#11]
e.g. - how do I convert this to a JSON object with fields/values?
```js
{ values_: [Object],
        fields_: [Object],
        lazyDeserializer_: {},
        deserializedFields_: [Object] }
```

**Comment by wajatimur** [comment]
Hi can you explain detail on what you were trying to do, it seems its already in JSON object. Are referring to Google protocol buffer?

**Comment by niftylettuce** [comment]
No longer need this.
