### ISSUE TITLE
phoneUtil.isValidNumbe retured an error for number "917888042551"

### ISSUE THREAD

**Issue by doronalon** [wajatimur/node-phonenumber#17]
phoneUtil.isValidNumbe returnred an error for number "917888042551"

The number  "917888042551" seem as valid according "https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html"  but the function "phoneUtil.isValidNumber" returned an error

var phone = require('node-phonenumber')
 
var phoneUtil = phone.PhoneNumberUtil.getInstance();
potentialPhoneNumber = phoneUtil.parse('917888042551', 'IN');
if (phoneUtil.isValidNumber(potentialPhoneNumber)) {
  
        result = potentialPhoneNumber
        console.log(JSON.stringify(potentialPhoneNumber));
       } else {
           error = new Error('Invalid number');
           console.log(error);

                    }

**Comment by wajatimur** [comment]
Ok, will have a look at it.

**Comment by wajatimur** [comment]
Can you try again with latest version v0.2.4, it seems pass the test.

**Comment by doronalon** [comment]
Thanks, with v0.2.4 it's working...

**Comment by wajatimur** [comment]
Welcome, good to hear that. Please ping me at twitter @azrijamil if got any urgent request.
