### ISSUE TITLE
Area code validation clarification

### ISSUE THREAD

**Issue by andresmatasuarez** [wajatimur/node-phonenumber#19]
Hi there

I've been inspecting the code for the past hour and I just couldn't find anything regarding area code validation, at least for US phone numbers.

My case is: I am trying to give users a more specific message for when they enter an invalid phone number. I was trying to send them "Invalid area code" for numbers like the following:
  - (200) 256 4566 (200 is not a valid area code)

I was using `getRegionCodeForNumber` returning null as a way to identify syntactically valid numbers that are semantically invalid.
```javascript
      const regionCode = getRegionCodeForNumber(parsedPhoneFromBody);
      if (!regionCode) {
           // throw error
      }
      // i will call isValidNumber later on to be 100% certain that number is indeed correct.
      const valid = isValidNumber(parsedPhoneFromBody);
```
However, I've just found that `(202) 156 4566` is invalid, not because of the area code but because the first digit after it is 1. And in that case, `getRegionCodeForNumber` returns null as well, making it undistinguishable from the previous case.

My question/feature proposal is: is there a way to have more specific errors like the one I'm trying to get? I don't mind contributing with its implementation

**Comment by wajatimur** [comment]
This package is based on Google libphonenumber, you can check the full doc here https://github.com/googlei18n/libphonenumber
