### ISSUE TITLE
Better documentation for phoneUtil.parse function.

### ISSUE THREAD

**Issue by shahzeb1** [wajatimur/node-phonenumber#20]
I'd be willing to create a PR for this, but I feel that the documentation is vague on what the second parameter of `parse(x,y)` should be. After some Googling, I think it should be the country code (since `MY` seems to be the country code for Malaysia).

Will add documentation about this.

**Comment by wajatimur** [comment]
Awesome, improvement are welcome.. Waiting for your PR
