### ISSUE TITLE
Tips on converting a closure library to nodejs for npm?

### ISSUE THREAD

**Issue by trusktr** [wajatimur/node-phonenumber#4]
Hello, would have any tips on how to convert this library, [webglearth2](https://github.com/webglearth/webglearth2), to nodejs to publish it on npm?

**Comment by wajatimur** [comment]
@trusktr the concept is simple, you have to create stub project (simply clone) of webglearth2 in you npm library folder then you have to bootstrap it by using `require` in you main npm file in this case might be `index.js`. Lastly you have to expose the webglearth2 object using `export`. If you inspect the `index.js` of node-phonenumber you can a s significant line of code from 3-5 and 80. Please let me know if you do start the npm lib.

**Comment by trusktr** [comment]
Cool, thanks for the tip. @wajatimur  You've made it sound fairly easy.

@klokan ^

**Comment by wajatimur** [comment]
@trusktr welcome.
