### ISSUE TITLE
Keeping up with libphonenumber

### ISSUE THREAD

**Issue by euskode** [wajatimur/node-phonenumber#5]
I was wondering if there are any plans to keep updating this project as new releases of googlei18n/libphonenumber are made. 

This is particularly important for numbers in developing countries. 

I am finding that there are a few specifically which I am unable to validate with node-phonenumber, but that appear perfectly valid when tested against the official project.

**Comment by wajatimur** [comment]
Yes it's, i will try to see if its possible to automate the build upon major commit of googlei18n/libphonenumber. If you have any suggestion please do let me know. Anyway thank to pointing me out regarding this issue.

**Comment by euskode** [comment]
Absolutely, that would be fantastic!

I actually am not entirely familiar with how the project is structured, but we've been using it for a while and so I thought I'd inquire about this.

**Comment by wajatimur** [comment]
Automatic build currently not possible, i will close this issue due to latest release of v0.2.1.

**Comment by euskode** [comment]
@wajatimur I thought I'd follow up since I am finding myself needed another update due to new area codes released in the US two months ago.

What was preventing the automatic builds from taking place? Is there more to it than bumping `node-phonenumber/lib/libphonenumber` every time a new release is made by Google?

Thanks in advance!
