### ISSUE TITLE
Updated libphonenumber

### ISSUE THREAD

**Issue by dadogerti** [wajatimur/node-phonenumber#7]
Hi There,

We are using googlei18n/libphonenumber which has been updated 5 days ago with new range of Bulgarian operator (Max Telecom). Since we are doing a project for Max Telecom , we will appreciate if you will update or use the latest libphonenumber release (release 7.0.7 ).

This request is very urgent , hopefully you can act fast.

Thanks in advanced,
Dado Gerti

**Comment by wajatimur** [comment]
@dadogerti I've pushed latest update.

**Comment by davida82** [comment]
Hi,

[from @dadogerti] Can you please create a new tag for the latest update?

Thanks,
Dado

**Comment by dadogerti** [comment]
Hi There,

We need you to create a tag for the latest update ? can you please help us ?

Dado Gerti

**Comment by euskode** [comment]
@dadogerti this is open source, you'll need to be patient.

@wajatimur publishing latest to NPM would be amazing.

**Comment by wajatimur** [comment]
Hi @euskode @dadogerti @davida82 , thanks buddy for reminding me. Sorry I was so busy lately, forget to do the necessary thing.

I have tag to the latest version and push it to NPM.
