### ISSUE TITLE
Fail to Require

### ISSUE THREAD

**Issue by edwinlunando** [wajatimur/node-phonenumber#8]
Hi! I want to use this library but, it give me errors when I tried to require it. I already put it in `package.json`

When I tried

```javascript
var phone = require('node-phonenumber');
```
It give me error. `ReferenceError: Can't find variable: setTimeout` Any idea?

**Comment by wajatimur** [comment]
Can you try to run a test `npm test` and post me the result.

**Comment by wajatimur** [comment]
I'm closing this as might be solved at your end.
